version: ">=5.8.1 || @head"
export: |
  project "ChaiScript"

      kind "StaticLib"

      zpm.export [[
          includedirs "include"
          cppdialect "C++14"

          filter "system:not windows"
              links {
                  "pthread",
                  "dl"
              }
          filter "system:windows"
              buildoptions "/bigobj"

          filter {}
      ]]