sudo: required
language: generic
matrix:
  include:
  - os: linux
    dist: trusty
    env: VERSION=6
  - os: linux
    dist: trusty
    env: VERSION=7
  - os: linux
    dist: trusty
    env: VERSION=5
  - os: osx
    osx_image: xcode8
    language: generic
install:
- source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/features/refactor/script/install-zpm.sh)"
script:
- cd test && zpm run test-definition ChaiScript
notifications:
  slack:
    secure: eM/FhUDPjLgUDRWNd8MLBu6+XXBg+KpkZjlPJVGZKeFPwRjrnAvcSfBU4o/Fdpz+PPl733dfjM2Hg+PoWgyctBcXsHDsJjDo6q0CE/slJMdKXCoVl+kYlmAQtVqhTIcWXDr3KSHHue3eSJWwULAwEX70J73lK8sFE+VCRnA2GV2hiUtXVoesZ2vt2YgqQWT2n0wvpmzMpCpI9meTum2EZoLxeNQviLzaLfSO4KpVTAEn+0iy+gXo1KnbF9FZ+q4P3Xx6n9eV1E0GrgLe58vloyqMVFJ31VICjn8piUmD0yWRaLSNUtKpq9XvGanVhuRwXIXZfFXab6WhGX1wBpu2Xet4fPGa/IXG3S2UjwFGvEO5P1/CHbfmZskEK1K+FJpPZxkP9GX9FhaZc3eyoSOPwEBnCiyXh8pI2bIMJbBnClYCuhv8UuVrAkZ+/RtNAh4FqqhN0qcAiAdyVda/wWJsaDazjIwLQPbxTY4c6AeRIK5/HTm5W4vEQ0QIm+XrLARNvUxUYhEab+Vh5ohaicY80rcwcJTxa16IDDESwIx9DbswwrOE589wTIW2yeey+RGlz5+732O28fSPTz/HClCY+buUYbFWcozjy76aaP706ZU4Ge0IWYylT8+oPewtKLeUBTiK9EcrCKBV0XpnWyyDNOJpuzYraVlp+Hp9a3yEzkQ=
